import { Flex, Tabs, TabList, Tab, Box, TabPanels, TabPanel, Accordion, AccordionItem, AccordionButton, AccordionIcon, AccordionPanel, Text } from "@chakra-ui/react";
import { useRouter } from "next/router";
import { FC } from "react";

const FAQ: FC = () => {
    const router = useRouter();
    const defaultIndex = router.asPath.includes("certifier_info") ? 2 : undefined;

    return (
      <>
        <Flex w={'full'} h={'20vh'} backgroundImage="/faq-banner.jpg" backgroundSize="cover" justify="center" align="center">
        <Text color="white" fontWeight={600} fontSize={["md", "2xl", "5xl"]} >
          Frequantly Asked Questions
        </Text>
        </Flex>
        <Flex justify="center" py="10" minH="45vh">
            <Tabs borderWidth='2px' h="fit-content" rounded='lg' p={["2", "3", "5", "6"]} variant='soft-rounded' isFitted w={["90%", "70%", "60%", "50%"]} boxShadow="0px 0px 15px 5px rgba(0,0,0,0.5)" colorScheme="purple">
                <TabList>
                    <Tab fontWeight='bold' fontSize={["xs", "md"]}>Frequent Questions</Tab>
                    <Tab fontWeight='bold' fontSize={["xs", "md"]}>Use Cases</Tab>
                </TabList>
                <TabPanels fontSize={["xs", "md"]}>
                <TabPanel>
                    <Accordion allowMultiple defaultIndex={defaultIndex ? [defaultIndex] : undefined}>
                        <AccordionItem>
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    What is SolEscrow?
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                SolEscrow is a powerful suite of tools designed to facilitate token sales and the development of decentralized ecosystems. It enables the creation of token sales with strict control parameters, liquidity locking, staking platforms, and lock as payment platforms.
                            </AccordionPanel>
                        </AccordionItem>

                        <AccordionItem>
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    How does SolEscrow help in token sales
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                SolEscrow allows for the creation of token sales platforms where you can set parameters such as minimum and maximum purchase amounts, fundraising deadlines, total fundraising limits, and liquidity allocation percentages. It also ensures security and investor trust by requiring liquidity locking and escrow services.
                            </AccordionPanel>
                        </AccordionItem>

                        <AccordionItem>
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    What is the Lock As Payment feature in SolEscrow?
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                The Lock As Payment feature in SolEscrow enables the creation of a platform where users can lock a predetermined quantity of tokens for a specified time in exchange for a token generated by the platform. This token can be used as payment for services, helping to tie your token to the services you offer.
                            </AccordionPanel>
                        </AccordionItem>

                        <AccordionItem>
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    Can you explain the Staking service offered by SolEscrow?
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                SolEscrow&apos;s Staking service allows for the creation of platforms where users can lock tokens for a set period to earn rewards. Users can configure parameters such as the maximum amount of lockable tokens, the duration of the staking period, and the annual percentage yield (APY). At the end of the staking period, users receive their locked tokens along with the staking rewards.
                            </AccordionPanel>
                        </AccordionItem>

                        <AccordionItem>
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    What are the features of the TradingBot offered by SolEscrow?
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                SolEscrow&apos;s TradingBot can be used as both a DApp and a Telegram bot. It offers functionalities such as Token Sniper, Buy/Sell orders, and Limit orders. Additionally, it integrates AntiMEV, AntiRug, and AI technologies to enhance security and efficiency in trading.
                            </AccordionPanel>
                        </AccordionItem>

                        <AccordionItem>
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    What are the differences between the Basic and Plus profiles for using the TradingBot in SolEscrow?
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                The Basic profile grants access to all trading bot functionalities, with a 1% transaction fee applied to each transaction. It&apos;s suitable for trying out the service. The Plus profile provides access to a private node for faster and optimal transactions, with no transaction fees. However, it requires a monthly subscription fee in ETH or one service token obtained through the Lock As Payment tool.
                            </AccordionPanel>
                        </AccordionItem>

                        <AccordionItem id="certifier_info">
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    Why in the app there is the SolEscrow address both in Receiver and Certifier by default?
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                SolEscrow has its own reserved team for verify and approve whether payments conditions have been meet. Contact the Admins in the Telegram channel and they will help both parties of the agreement.
                            </AccordionPanel>
                        </AccordionItem>
                    </Accordion>
                </TabPanel>
                <TabPanel>
                    <Accordion>
                        <AccordionItem>
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    Verifiers Service
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                Here, our role is limited to verifying the pre-sale conditions. The address provided by the creator of the guarantee fund will be used for distributing the funds in case confirmation is not obtained.
                                <br></br><br></br>In this case, the owner of the private sale enters into an insurance agreement with the owner of an investment group. It will be our responsibility to verify the terms and conditions of the insurance. 
                                <br></br><br></br>In the event that we need to deny the release of funds, it will be the responsibility of the owner of the investment group to redistribute the funds as compensation for the investors. In this case, we will request 1% of the funds as payment for the service, or 1 service token. 
                                <br></br><br></br>The payment method will be available with the release of the Payment Lab feature, which will enable Lock As Payment through our token.
                            </AccordionPanel>
                        </AccordionItem>

                        <AccordionItem>
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    Software as Service
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                In this scenario, both the verifier of the guarantee fund conditions and the person in charge of redistributing the funds in case of non-approval of the private sale are external individuals specified by the fund creator.
                                <br></br><br></br>In this case, the owner of the private sale enters into an insurance agreement with the owner of an investment group and designates an external verifier, who may be a well-known entity in the DeFi space, to act as a mediator between the parties. 
                                <br></br><br></br>In this scenario, we will only provide the service, and no payment will be required. The compensation for the verifier is freely determined between the parties.
                            </AccordionPanel>
                        </AccordionItem>

                        <AccordionItem>
                            <AccordionButton>
                                <Box as="span" flex='1' textAlign='left' fontWeight='bold'>
                                    Full Service
                                </Box>
                                <AccordionIcon />
                            </AccordionButton>
                            <AccordionPanel pb={4}>
                                In this mode, we take responsibility for verifying compliance with the pre-sale conditions and acquire the guarantee funds if those conditions are not met. 
                                <br></br><br></br>Subsequently, it is our task to divide any funds to compensate the investors. In this case, the owner of the private sale entrusts us with the management of the insurance fund for their investors. 
                                <br></br><br></br>It will be our responsibility to verify the terms and conditions of reimbursement in case it is necessary. In this case, we will request 1% of the funds as payment for the service, or 1 service token. 
                                <br></br><br></br>The payment method will be available with the release of the Payment Lab feature, which will enable Lock As Payment through our token.
                            </AccordionPanel>
                        </AccordionItem>
                    </Accordion>
                </TabPanel>
                </TabPanels>
            </Tabs>
        </Flex>
      </>
    );
  };
  
  export default FAQ;
  